server:
  port: 8888

eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/arpit108/scf-config-repository.git


security:
  basic:
    enabled: true
  user:
    name: arpit
    password: bhargava
