server:
  port: 8888

eureka:
  client:
    service-url:
      defualtZone: http://localhost:8761/eureka

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arpit108/scf-config-repository.git

